version: '3'

services:

  app:
    build: .docker/node
    entrypoint: ./.docker/entrypoint.sh
    container_name: nextjs
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - .:home/node/app

  db:
    build: .docker/postgres
    restart: always
    tty: true
    volumes:
      - .docker/db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nestapi

  pgadmin:
    image: dpage/pgadmin4
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=123456
    ports:
      - 9000:80
    depends_on:
      - db




